"""
Educational implementation of X25519 key exchange.

This module implements the core X25519 scalar multiplication operation using:
- scalar clamping
- arithmetic modulo p = 2^255 - 19
- the Montgomery ladder

Main idea:
    X25519(private_key, public_key) -> 32-byte result

The same function is used for two purposes:
1. Public key generation:
       public_key = X25519(private_key, BASE_POINT)

2. Shared secret derivation:
       shared_secret = X25519(my_private_key, other_party_public_key)

Important:
    This implementation is for educational purposes only.
    Python integer operations are not guaranteed to be constant-time, so this
    code should not be used in production cryptographic systems.
"""


# ---------------------------------------------------------------------------
# X25519 / Curve25519 constants
# ---------------------------------------------------------------------------

# The prime modulus of the finite field used by Curve25519.
# Almost all arithmetic in X25519 is done modulo this prime.
#
# This connects directly to modular arithmetic:
#     value mod p
#
# where:
#     p = 2^255 - 19
P = 2**255 - 19


# A24 is a curve-specific constant used by the Montgomery ladder formulas.
#
# For Curve25519:
#     A = 486662
#     A24 = (A - 2) / 4 = 121665
#
# We use this constant inside the ladder step when updating z_2.
A24 = 121665


# X25519 keys and outputs are always 32 bytes.
KEY_SIZE = 32


# The standard X25519 base point.
#
# In X25519, a public key is generated by multiplying the private scalar
# by this fixed base point.
#
# The base point is the u-coordinate 9 encoded as 32 little-endian bytes.
BASE_POINT = bytes([9]) + bytes(31)


# ---------------------------------------------------------------------------
# Input validation
# ---------------------------------------------------------------------------

def _validate_32_bytes(value: bytes, name: str) -> None:
    """
    Validate that a given input is exactly 32 bytes.

    Why this matters:
        X25519 works with 32-byte private keys, public keys, and outputs.
        If we accept shorter or longer inputs, the algorithm may produce
        invalid results or hide bugs in the implementation.

    Args:
        value:
            The byte value we want to validate.

        name:
            A human-readable name used in the error message.

    Raises:
        TypeError:
            If value is not a bytes object.

        ValueError:
            If value is not exactly 32 bytes.
    """
    if not isinstance(value, bytes):
        raise TypeError(f"{name} must be bytes")

    if len(value) != KEY_SIZE:
        raise ValueError(f"{name} must be exactly {KEY_SIZE} bytes")


# ---------------------------------------------------------------------------
# Scalar clamping
# ---------------------------------------------------------------------------

def clamp_scalar(private_key: bytes) -> int:
    """
    Clamp a 32-byte private key into a valid X25519 scalar.

    What is clamping?
        Clamping means modifying specific bits of the private key before using
        it as a scalar in the Montgomery ladder.

    X25519 clamping rules:
        1. Clear the lowest 3 bits.
        2. Clear the highest bit.
        3. Set the second-highest bit.

    In code:
        scalar[0]  &= 248
        scalar[31] &= 127
        scalar[31] |= 64

    Why this matters:
        The raw private key is random bytes.
        X25519 requires the scalar to have a specific bit pattern that avoids
        weak edge cases and makes the scalar suitable for the Curve25519 group
        structure.

    Args:
        private_key:
            A 32-byte private key.

    Returns:
        The clamped scalar as an integer in little-endian format.
    """
    _validate_32_bytes(private_key, "private_key")

    # bytearray lets us modify individual bytes.
    scalar = bytearray(private_key)

    # Clear the lowest 3 bits of the first byte.
    scalar[0] &= 248

    # Clear the highest bit of the last byte.
    scalar[31] &= 127

    # Set the second-highest bit of the last byte.
    scalar[31] |= 64

    # X25519 uses little-endian encoding.
    return int.from_bytes(scalar, byteorder="little")


# ---------------------------------------------------------------------------
# Public key / u-coordinate decoding
# ---------------------------------------------------------------------------

def decode_u_coordinate(public_key: bytes) -> int:
    """
    Decode a 32-byte X25519 public key into an integer u-coordinate.

    Background:
        In X25519, a public key is the u-coordinate of a point on the
        Montgomery curve. This is why X25519 is often described as using
        "X-only" arithmetic.

    X25519 decoding rule:
        The most significant bit of the final byte is ignored before decoding.

    Why this matters:
        The public key arrives as bytes, but the Montgomery ladder works with
        integers modulo p. Therefore, we need to convert the byte representation
        into an integer field element.

    Args:
        public_key:
            A 32-byte encoded u-coordinate.

    Returns:
        The decoded u-coordinate as an integer modulo P.
    """
    _validate_32_bytes(public_key, "public_key")

    # Copy the bytes so we do not mutate the caller's input.
    u = bytearray(public_key)

    # Ignore the most significant bit of the final byte.
    u[31] &= 127

    # Convert little-endian bytes to integer and reduce modulo P.
    return int.from_bytes(u, byteorder="little") % P


# ---------------------------------------------------------------------------
# Conditional swap
# ---------------------------------------------------------------------------

def conditional_swap(swap: int, first: int, second: int) -> tuple[int, int]:
    """
    Conditionally swap two integer values.

    If swap == 1:
        returns (second, first)

    If swap == 0:
        returns (first, second)

    Why not use a normal if-statement?
        In cryptography, branching on secret bits can leak timing information.
        Montgomery ladder implementations usually use conditional swaps to
        avoid secret-dependent branches.

    Important educational note:
        This function is written in a branchless style, but Python itself is
        not guaranteed to be constant-time. Therefore, this is useful for
        learning the structure of the algorithm, not for production security.

    Args:
        swap:
            Either 0 or 1.

        first:
            First integer value.

        second:
            Second integer value.

    Returns:
        The possibly swapped pair of integers.
    """
    mask = -swap
    dummy = mask & (first ^ second)

    first ^= dummy
    second ^= dummy

    return first, second


# ---------------------------------------------------------------------------
# Core X25519 operation
# ---------------------------------------------------------------------------

def x25519(private_key: bytes, public_key: bytes) -> bytes:
    """
    Perform the core X25519 scalar multiplication operation.

    Conceptually:
        result = private_key * public_key

    But this is not normal integer multiplication.
    It is scalar multiplication on Curve25519 using the Montgomery ladder.

    This function is used for both:

    1. Public key generation:
           public_key = x25519(private_key, BASE_POINT)

    2. Shared secret derivation:
           shared_secret = x25519(my_private_key, other_public_key)

    High-level algorithm:
        1. Clamp the private key into a valid scalar.
        2. Decode the public key as a u-coordinate.
        3. Initialize the Montgomery ladder state.
        4. Process the scalar bit by bit from most significant to least.
        5. Use modular arithmetic over p = 2^255 - 19.
        6. Convert the final projective coordinate X/Z back into affine form.
        7. Return the result as 32 little-endian bytes.

    Args:
        private_key:
            A 32-byte private key.

        public_key:
            A 32-byte public u-coordinate.

    Returns:
        A 32-byte X25519 result.
        This result is either a public key or a shared secret, depending on
        the public_key input.
    """
    # Convert the private key bytes into a clamped scalar integer.
    scalar = clamp_scalar(private_key)

    # Decode the other party's public key, or the base point, into an integer.
    x_1 = decode_u_coordinate(public_key)

    # Montgomery ladder state.
    #
    # The ladder internally represents coordinates as projective coordinates:
    #     x = X / Z mod P
    #
    # This avoids expensive modular division during every ladder step.
    x_2 = 1
    z_2 = 0

    x_3 = x_1
    z_3 = 1

    # Tracks whether we need to swap the ladder states.
    swap = 0

    # Process the scalar from bit 254 down to bit 0.
    #
    # X25519 uses 255 scalar bits.
    for bit_index in reversed(range(255)):
        current_bit = (scalar >> bit_index) & 1

        # Decide whether the current ladder state should be swapped.
        swap ^= current_bit

        # Swap both X and Z coordinates consistently.
        x_2, x_3 = conditional_swap(swap, x_2, x_3)
        z_2, z_3 = conditional_swap(swap, z_2, z_3)

        # Save the current bit for the next iteration.
        swap = current_bit

        # -------------------------------------------------------------------
        # Montgomery ladder formulas
        # -------------------------------------------------------------------
        #
        # This section performs one ladder step.
        # It updates two internal states using only modular addition,
        # subtraction, multiplication, and squaring.
        #
        # All operations are reduced modulo P.
        # -------------------------------------------------------------------

        a = (x_2 + z_2) % P
        aa = (a * a) % P

        b = (x_2 - z_2) % P
        bb = (b * b) % P

        e = (aa - bb) % P

        c = (x_3 + z_3) % P
        d = (x_3 - z_3) % P

        da = (d * a) % P
        cb = (c * b) % P

        x_3 = ((da + cb) * (da + cb)) % P
        z_3 = (x_1 * ((da - cb) * (da - cb))) % P

        x_2 = (aa * bb) % P
        z_2 = (e * (aa + A24 * e)) % P

    # Final swap after the loop.
    x_2, x_3 = conditional_swap(swap, x_2, x_3)
    z_2, z_3 = conditional_swap(swap, z_2, z_3)

    # Convert from projective coordinates back to the normal affine coordinate:
    #
    #     x = X / Z mod P
    #
    # In modular arithmetic, division by Z means multiplication by Z inverse:
    #
    #     x = X * Z^(-1) mod P
    #
    # Because P is prime, we can compute Z^(-1) using Fermat's little theorem:
    #
    #     Z^(-1) = Z^(P - 2) mod P
    z_2_inverse = pow(z_2, P - 2, P)
    result = (x_2 * z_2_inverse) % P

    # Return the result as 32 little-endian bytes.
    return result.to_bytes(KEY_SIZE, byteorder="little")


# ---------------------------------------------------------------------------
# Public key generation helper
# ---------------------------------------------------------------------------

def generate_public_key(private_key: bytes) -> bytes:
    """
    Generate an X25519 public key from a private key.

    The public key is calculated by multiplying the private scalar by the
    standard X25519 base point.

    In formula form:
        public_key = x25519(private_key, BASE_POINT)

    Args:
        private_key:
            A 32-byte private key.

    Returns:
        A 32-byte X25519 public key.
    """
    return x25519(private_key, BASE_POINT)